name: Check Pull Request
on: workflow_dispatch # just manual triggers for now
jobs:
  check:
    runs-on: [ubununtu-latest]
    # TODO: renovate to keep all of this up to date
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.24.2"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
      - run: |
          go mod tidy
          go test ./...
