name: Release
on:
  push:
    branches:
      - main
    paths:
      - "VERSION"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.24.2"
      - name: Build
        run: |
          go mod tidy
          go build -ldflags "-X main.version=$(cat VERSION)" -o liet .
      - name: Tag Version
        run: |
          VERSION=$(cat VERSION)
          git tag $VERSION
          git push origin $VERSION
      - name: Get Version
        id: get_version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          files: |
            liet
permissions:
  contents: write
